### PR TITLE
Added security sample in CS for browser policies

### PR DESCRIPTION
**Pull request by PEM--**

### CODE REVIEW

**Comment by nicolaslopezj** [comment]
Thanks a lot, but the sample must be in javascript, not everyone knows coffeescript. 
A lot of people that use orion are beginners and the not necessary know coffeescript.

**Comment by timfam** [comment]
@nicolaslopezj I disagree, If someone else wants to compile into JS and do a PR that is fine. It's like saying .LESS snippets not welcome. This will deprive the .LESS people useful snippets. All variants has to be welcome

**Comment by nicolaslopezj** [comment]
All code **must** be written in the same style, thats a golden rule of open source projects. 
It's not so important if someone uses less or sass, this is not a css project.
Orion is a serious project and we can't mix languages, we must keep the code clean and organized.

**Comment by rwatts3** [comment]
I second Nicolas response @timfam discussions like this are best kept in a more private setting such as the internal discussion board.  Right now the contradicting response will appear as unorganized and confusing to followers.  Let's go with Nicolas direction.  And discuss  this further in internal discussion.

**Comment by timfam** [comment]
then meet me at gitter

**Comment by PEM--** [comment]
@timfam, @nicolaslopezj & @rwatts3, you're right.

It should be in JS for respecting consistency. But delivering in CS has another advantage, it shows that Orion is fully useable in this language.

If consistency matters more to you than foreign language friendliness, I can translate it in JS. No pb. Just ask.

Note that for another framework, we provide the both languages. Check this out: http://famous-views.meteor.com/features/iron-router

**Comment by timfam** [comment]
We discussed the issue intensively and we want a win-win, with both js and
cs variants available.  So default will be js and variant CS. I guess we
need to get an online compiler or something to make this work.

**Comment by nicolaslopezj** [comment]
@PEM-- in other topic, I think in this case it's better to have a tutorial: "how to improve the security in your Orion application". I cloud have more exposure. 
The process is the same but in orionjs/tutorials

**Pull request merged**
